language: python

matrix:
  include:
    - python: 3.6
      env: TOXENV=py,codecov-travis

before_cache:
  - |
      coverage erase
      rm -f $HOME/.cache/pip/log/debug.log

cache:
    directories:
        - $HOME/.cache/pip
        - $TRAVIS_BUILD_DIR/.tox

install:
    - pip install -U pip tox

before_script:
    - |
      mkdir -p $HOME/.config/matplotlib
      echo 'backend      : agg' > $HOME/.config/matplotlib/matplotlibrc

script:
    - tox

notifications:
  email: false
  irc: "chat.freenode.net#fluiddyn"
